# Generated by Django 5.0.7 on 2024-07-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailmessage',
            old_name='send_date',
            new_name='sent_date',
        ),
    ]
